### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by natxopedreira** [balrog-kun/fpv-stream-to-vr#1]
Hi

I just found this repo, im playing with a wifibroadcast fpv and using gstreamer with a video mixer to view the stream in oculus. And saw your approach with python+gtk+gstreamer and i want to try it

I tryed to compile your repo and get an error

File "stream.py", line 186, in <module>
GTK_Main(w, h, x, y)
TypeError: **init**() takes exactly 6 arguments (5 given)

Thanks!!

**Comment by natxopedreira** [comment]
my mistake, im new to python, works ok! it compiles now removing the input_path from the constructor as i want to use wifibroadcast as input and i don't have any webcam attached.

im getting now a black screen and the wifibroadcast its ok as i can see it with a gstreamer pipe

i will dig a bit to see if see what im doing wrong

**Comment by balrog-kun** [comment]
Hi natxo,
It was actually an error in my code, I had forgotten to commit the removal of the parameter from the constructor.

BTW I haven't worked with wifibroadcast myself yet, but I added this parameter to be used the following way:

sudo ./rx -b 8 -r 4 -f 1024 wlan0 | ./stream.py wifibroadcast

instead of sudo ./rx ... | gst-launch-1.0 ...
I hope you get it to work, please let me know if any other fix is needed.

**Comment by natxopedreira** [comment]
Thanks, its working, i see the stream now.

one issue its that the gst part does not respect the width that you are setting in the pipe, it does a "scale to fit" which its not because i want to set a width different to w/2.

can you tell me your gstreamer, gtk, python version?

**Comment by natxopedreira** [comment]
solved that using add-borders=1 and you have to set a height > real height, seems like something wreid in gstreamer. now it would be super if can use a shader or something like to correct barrel of the rift

**Comment by balrog-kun** [comment]
I'm using gstreamer 1.4.5, gtk 3.14.12 and python 2.7.9.

Can you describe exactly which of the images is being resized by gstreamer and to what size?

I use a fish-eye lens (150 deg I think) and it looks just right in the oculus.  It seems that the distortion added by the oculus is the exact reverse of that of the lens.

**Comment by natxopedreira** [comment]
thanks

i will try to explain myself better, imagine that want to use a resolution of 1280x720 without scaling, in a bigger screen like 1920x1080
- for each eye i want 1280/2 = 640 so 640x720 each eye
- half screen measures 1920/2 = 960

right now if i do this i will see the video in 960 width not 640 so im getting upscale

i have to set "add-borders=1" in the scale element of the pipe and set a height bigger than the correct to preserve movie ratio, so i have to say height bigger than (360) in this case if i say the correct number (360) i get the upscaling and width is ignored. I don't find too much sense for that, maybe its from my version of gstreamer, im runnging fresh ubuntu 14 gstreamer 1.2.4

Im thinking in use a lens with more fov like you say also because the fov its too narrow seems like wearing binoculars. its a workarround but the shader will also help to chromatic aberration in dk2....

There is a glshader element for gstreamer but i don't know in wich version exist right now.

FYI. in a german thread of wifibroadcast someone managed to get that running in 2.3 ghz band

Your app works great!!, as fast as the previos pipeline with gstlanch + videmixer that i was using but with a fullscreen and adjust settings

**Comment by balrog-kun** [comment]
Hi natxo, sorry for slow reply.

I think I see what the problem is, but that occurs only when you modify the width to be different than w/2, right?  I have been thinking of allowing the user to scale the video using the up/down arrow keys, this would let you simulate the FOV of a Fatshark or Headplay goggles in a Rift.  I know some FPV pilots prefer a smaller FOV that 110 degrees.  Would this solve your problem?

I'll do this and I'll add a README to document the current key bindings.

BTW it looks like add-borders is true by default: http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-videoscale.html

Cheers

**Comment by balrog-kun** [comment]
BTW I have seen a pixel shader-based deformation trick for gstreamer posted somewhere on stackoverflow.  It was used specifically to send narrow-angle video to a DK2.

**Comment by natxopedreira** [comment]
Hi

I have been working on this a little, i forked your repo and upload a 3d version. I tried in a compute module using 2 cameras with a separation between the center of the lenses of 62mm.

With this setup you have 3d video and its an amazing effect, you have to try this, its amazing, i spend 20 minutes looking at my hand in 3d :) .

Yes the behavior its like you say, the key strokes to change the scale its great idea !!!, i added also keys to displace the y position of each camera (have to upload that to github). 

As you say it can be useful for people with other "glasses", the problem with the oculus approach its that you have to run on a "normal pc" it won't work on a rpi or something like that so no a very portable solution (did you know if it will work on a intel stick or something like this ???)

One issue that im getting its that sometimes the code crashes on startup, saying something like the X device its not available, i have to dig more on this.

Im going to receive two 160º cameras on wednesday so i can test the "pseudo barrel correction"
http://www.sainstore.de/camera-module-board-5mp-160-wide-angle-fish-eye-lenses-for-raspberry-pi.html/

Im testing it with a dk1 headset, and this doesn't have the chromatic aberration like the dk1 or at least if exist its not so visible.

I tried a lot of times to use the glshader element in raspberry but i never managed to get it working, its the element available on your gstreamer version?

Some shaders resources
https://lubosz.wordpress.com/2013/08/28/view-side-by-side-stereoscopic-video-with-gstreamer-and-oculus-rift/

DK1 shaders
https://github.com/andreasmuller/ofxOculusRift/tree/master/example-OculusRiftRendering/bin/data/Shaders

DK2 shaders
https://github.com/obviousjim/ofxOculusDK2/tree/master/example-OculusRiftRendering/bin/data/Shaders

GSLS barrel
https://github.com/pion3er/RiftIt/tree/master/data

Thanks!!!!!

**Comment by natxopedreira** [comment]
Just one question, sometimes i suffer an extrange issue.

Its possible that somewhere in the gst pipe exist something like a buffer? 

 im seeing frames from the past, its like the latency sometimes goes up to several seconds, do you know what can be the cause?

**Comment by balrog-kun** [comment]
> I have been working on this a little, i forked your repo and upload a 3d version. I tried in a compute module using 2 cameras with a separation between the center of the lenses of 62mm.

That's cool, I'm definitely going to try it at some point but for now I only have analog video and getting started with wifibroadcast.

Do you use wifibroadcast?  How do you connect the two cameras to a Raspberry Pi?  It only has one CSI interface, right?  BTW why do you prefer to flip the video in your version rather than use xrandr rotation?

> As you say it can be useful for people with other "glasses", the problem with the oculus approach its that you have to run on a "normal pc" it won't work on a rpi or something like that so no a very portable solution (did you know if it will work on a intel stick or something like this ???)

I don't know... in theory the Oculus works with anything that has a HDMI output (or VGA, DP, etc. with an adapter).

> One issue that im getting its that sometimes the code crashes on startup, saying something like the X device its not available, i have to dig more on this.

Yes, I see the same thing.  Yesterday I added a README.md to the repository where I mention this, https://github.com/balrog-kun/fpv-stream-to-vr/blob/master/README.md

I have seen other random problems with gstreamer so I think it's just gstreamer bugs... (for example if I don't include the "deinterlace" element before "videomixer" for analog video)

> Im going to receive two 160º cameras on wednesday so i can test the "pseudo barrel correction"

With wide-angle cameras you shouldn't need any correction I believe, only with narrow-angle.

I do have the glshader plugin but gst-inspect-1.0 indicates it comes from the "bad" plugins package on Ubuntu:
apt-get install gstreamer1.0-plugins-bad

> im seeing frames from the past, its like the latency sometimes goes up to several seconds, do you know what can be the cause?

Hmmm, I've not seen this, maybe it's a compression artifact related to wifibroadcast key frames or something like that...

BTW I would like to include your 3D support in my repository but I think I will need to support the "--switch" type of command line switches to make it flexible.

**Comment by natxopedreira** [comment]
- yep im using wifibroadcast because i want a quality image and analog approach has lower resolution
- im using a compute module with the development board (it has support for two CSI cameras), even raspivid has beed updated to support 3d video output
- im running a dk1 so i don't need to rotate the screen, i receive the video in sbs format so for each eye i need to rotate +  crop for each eye. For the dk2 you have to rotate the screen (its a bug or something like that in the oculus driver)
- I read a little and the queue element seem to be the cause for the extrange "buffer latency effect", right now i put in the queue element "max-size-buffer=2" and seems to be ok

I will include the console commands like --switch and the newers like "scale" and upload that to the repo

Im still working on this, now i want to switch to 2.3 ghz so i can use my spektrum rc

**Comment by natxopedreira** [comment]
I think you should post a link to this repo on the wifibroadcast blog, i posted about the 3d approach and im sure that this app its very usefull for them. I don't post the url because its your merit and my version its  based on yours, i only modify it to suit my needs
